import Head from "next/head";
// import Header from "../components/Header";
import Hero from "../components/Hero";
import Services from "../components/Services";
import WhoWeAre from "../components/WhoWeAre";
import ComingSoon from "../components/ComingSoon";

export default function Home() {
    return (
      <div className="w-4/5 mx-auto">
        <Head>
          <title>TechXent</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <Header /> */}
        <main className="pt-24 lg:pt-32 2xl:pt-44 flex flex-col gap-y-12 xl:gap-y-20 ">
          <Hero />
          <WhoWeAre />
          <Services />
          <ComingSoon />
        </main>
      </div>
    );
  }
  